import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const edit=(p,fn)=>fs.writeFileSync(p,fn(read(p)));
const ds=JSON.parse(read('architecture/definitions.json'));
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=ds.map((d,i)=>`<article class="atlas-card" data-atlas-card><span class="atlas-index">${String(i+1).padStart(2,'0')} / SYSTEM MAP</span><h2>${e(d.title)}</h2><span class="archify-status">${e(d.status)}</span><p>${e(d.scope)}</p><div class="atlas-map-links">${[['architecture','Architecture'],['logic','Logic flow'],['code','Code flow'],['data','Data flow']].map(([k,v])=>`<a href="maps/${d.id}-${k}.html">${v} ↗</a>`).join('')}</div><a class="atlas-case-link" href="../projects/${d.slug}#archify-title">Read the case and sources →</a></article>`).join('');
fs.writeFileSync('architecture/index.html',`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Architecture Atlas | Yashu Sharma</title><meta name="description" content="Nine systems, 36 explorable Archify maps, and explicit boundaries between implemented, scaffolded, and proposed work."><link rel="canonical" href="https://yashumani.github.io/architecture/"><script src="../js/theme-init.js"></script><link rel="stylesheet" href="../css/style.css"><link rel="stylesheet" href="../css/media.css"><link rel="stylesheet" href="../css/archify.css"></head><body><a class="skip-link" href="#main-content">Skip to content</a><header class="site-header"><div class="wrap nav-shell"><a class="brand" href="../index.html"><span class="brand-mark" aria-hidden="true">YS</span><span>Yashu Sharma</span></a><nav class="site-nav" aria-label="Primary navigation"><a href="../index.html#work">Work</a><a href="index.html" aria-current="page">Architecture</a><a href="../resume.html">Resume</a><button class="theme-toggle" type="button" aria-label="Use dark mode">◐</button></nav></div></header><main id="main-content" class="wrap atlas-main"><div class="atlas-hero"><p class="mono-label">Architecture atlas / Built with Archify</p><h1>See how the<br>systems fit together.</h1><p>Start with the component map. Follow the logic, code, or data path. Each diagram keeps its source and implementation boundary visible.</p><div class="atlas-strip"><span>09 systems</span><span>36 interactive maps</span><span>Editable JSON + image export</span></div></div><div class="atlas-filter"><label><span class="sr-only">Find a system</span><input type="search" data-atlas-search placeholder="Find a system or capability…" aria-label="Find a system"></label><output data-atlas-count aria-live="polite">9 of 9 systems</output></div><section class="atlas-grid" aria-label="System architecture maps">${cards}</section><div class="atlas-note"><strong>Read the boundary before the diagram.</strong><p>These maps redraw the published portfolio cases; they are not a fresh live-deployment audit. The full readers support zoom, search, focus, theme switching, and export. Case pages include readable HTML alternatives and load only one preview at a time.</p><p><a href="README.md">Source method and generator version</a> · <a href="LICENSE-ARCHIFY.txt">Archify license</a> · <a href="../index.html">Return to profile</a></p></div></main><script src="../js/main-core.js"></script><script src="../js/archify.js"></script></body></html>\n`);
if(process.env.ARCHIFY_HOME)fs.copyFileSync(process.env.ARCHIFY_HOME+'/LICENSE','architecture/LICENSE-ARCHIFY.txt');
edit('index.html',s=>{
 if(!s.includes('class="atlas-entry"'))s=s.replace('<div class="work-group reveal" data-work-group="professional">','<a class="atlas-entry" href="architecture/index.html">Explore the architecture atlas — 9 systems, 36 maps →</a>\n        <div class="work-group reveal" data-work-group="professional">');
 if(!s.includes('css/archify.css'))s=s.replace('</head>','<link rel="stylesheet" href="css/archify.css">\n</head>');return s;
});
edit('professional-profile.html',s=>{
 if(!s.includes('architecture/maps/harnesslab-architecture.html')){const start=s.indexOf('<div class="pipeline-track harness-track">'),end=s.indexOf('</div>',start)+6;if(start<0)throw new Error('Presentation harness anchor changed');s=s.slice(0,end)+'<p><a href="architecture/maps/harnesslab-architecture.html" target="_blank" rel="noopener">Explore the Archify system map ↗</a></p>'+s.slice(end);}return s;
});
edit('scripts/validate-site.mjs',s=>s.replace("const htmlFiles = allFiles.filter((file) => file.endsWith('.html'));","// Delivered Archify readers have an independent schema/hash/renderer contract.\nconst htmlFiles = allFiles.filter((file) => file.endsWith('.html') && !file.startsWith('architecture/maps/'));\nif (fileSet.has('architecture/catalog.json')) await import('./check-archify.mjs');"));
edit('tests/portfolio-content.mjs',s=>s.replace("const diagram = page.locator('.flow-showcase');","const diagram = page.locator('.archify-workspace');").replace("await expect(diagram.locator('.architecture-stage')).toHaveCount(4);","await expect(diagram.locator('[role=tab]')).toHaveCount(4);").replace("await expect(diagram.locator('.architecture-node')).toHaveCount(16);","await expect(diagram.locator('.archify-text')).toHaveCount(4);").replace("await expect(diagram.locator('.flow-lane:not([hidden])')).toHaveCount(3);","await expect(diagram.locator('.archify-scope')).toBeVisible();").replaceAll("await expect(page.locator('.flow-showcase .architecture-stage')).toHaveCount(4);","await expect(page.locator('.archify-workspace [role=tab]')).toHaveCount(4);").replaceAll("await expect(page.locator('.flow-showcase .architecture-node')).toHaveCount(16);","await expect(page.locator('.archify-text')).toHaveCount(4);").replaceAll("await expect(page.locator('.flow-showcase .flow-lane:not([hidden])')).toHaveCount(3);","await expect(page.locator('.archify-scope')).toBeVisible();"));
edit('package.json',s=>{const j=JSON.parse(s);if(!j.scripts['check:syntax'].includes('node --check js/archify.js'))j.scripts['check:syntax']+=' && node --check js/archify.js && node --check scripts/build-archify.mjs && node --check scripts/integrate-archify.mjs && node --check scripts/check-archify.mjs && node --check tests/archify.spec.mjs';j.scripts['build:architecture']='node scripts/build-archify.mjs';j.scripts['check:architecture']='node scripts/check-archify.mjs';return JSON.stringify(j,null,2)+'\n';});
